[package]
name = "m31jubjub"
version = "0.1.0"
edition = "2021"

[dependencies]

p3-mersenne-31 = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-field = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-poseidon2 = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}
p3-symmetric = {git="https://github.com/zeropoolnetwork/Plonky3.git", branch="fork/feature/cfft-symmetric-compatibility"}


primitives = {git="https://github.com/zeropoolnetwork/sharded-storage.git", branch="main"}

ark-ff = "0.4.2"
num-bigint = "0.4.6"
sha3 = "0.10.8"

[dev-dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
bincode = "1.3"
rand = "0.8.5"